### ISSUE TITLE
Make isInitDoing() and isInitDone() permanent 

### ISSUE THREAD

**Issue by wilstenholme** [baxter-oop/baxter-app#21]
Record those Boolean values in Preferences.

**Comment by JCharante** [comment]
Maybe make a method in FlexActivity that checks all tasks and sees if it should reset the boolean values to false?

**Comment by wilstenholme** [comment]
`Yeah` but make it recordable first.

**Comment by JCharante** [comment]
recordable?

**Comment by wilstenholme** [comment]
saved in preferences

**Comment by JCharante** [comment]
Of course
